args=None #Place holder for p2pool args
db_username='DBuser' #database username
db_password='DBpasswd' #database password
db_location='localhost' #database location
db_name='p2pmining' #database name
shares_per_shift=100000 #total shares per shift
shifts_pplns=10 #Number of shifts that still get payed
mining_address='1Mdq4dqoxi8N8An3M2gfZCt9pNYGZ927uD' #payout address
primary_coin='Bitcoin' #primary coin name
primary_coin_abbrv='BTC' #primary coin abbreviation
pool_fee=0.1 #fee paid to pool in % of rewards (pool will need to pay transaction fees)
